
import logger from '../core/logger.js';

/**
 * MODULE 2: LE META-PLANIFICATEUR STOÏQUE
 * Rôle: Filtre de Réalisme.
 * "Minimal Effort -> Maximal Yield".
 */
class StoicPlanner {
  init() {
    logger.info('[STOIC PLANNER] 📐 Logic Gate Active.');
  }

  /**
   * Reviews a plan generated by Razor.
   * Rejects over-complicated or vague steps.
   */
  validatePlan(plan) {
    if (!plan || !plan.stages) return plan;

    logger.info(`[STOIC PLANNER] ⚖️ Reviewing Plan: ${plan.stages.length} stages.`);

    const optimizedStages = [];
    let rejectedCount = 0;

    for (const stage of plan.stages) {
        // RULE 1: NO "HOPE" STRATEGY
        if (stage.id && stage.id.toLowerCase().includes('hope')) {
            rejectedCount++;
            continue;
        }

        // RULE 2: SIMPLICITY (Occam's Razor)
        // If a stage has > 10 tasks, it's too complex. Split it or reject.
        if (stage.tasks.length > 10) {
            logger.warn(`[STOIC PLANNER] ✂️ Trimming complex stage: ${stage.id}`);
            stage.tasks = stage.tasks.slice(0, 5); // Take top 5
        }

        optimizedStages.push(stage);
    }

    if (rejectedCount > 0) {
        logger.info(`[STOIC PLANNER] 🗑️ Purged ${rejectedCount} illogical stages.`);
    }

    return { ...plan, stages: optimizedStages, stoic_validation: true };
  }
}

export const stoicPlanner = new StoicPlanner();
